baseURL = 'https://yogurtthehor.se/'
title = 'Yogurt The Horse'
theme = "shibui-ygrt"
defaultContentLanguage = 'en'

[outputs]
  home = ['html', 'rss']
  section = ['html', 'rss']
  taxonomy = ['html']
  term = ['html']

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false

      [markup.goldmark.parser.attribute]
        block = true
        title = true

[params]
  author = "Yogurt"
  email = "yegor@yogurtthehor.se"

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
  [languages.ru]
    languageName = "Russian"
    weight = 2

[caches]
  [caches.images]
    dir = ':cacheDir/images'
