# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Shibui (渋い)-ygrt"
license = "MIT"
licenselink = "https://github.com/ntk148v/shibui/blob/main/LICENSE"
description = "Shibui is a yet another minimalistic Hugo theme (modified by ygrt)"
homepage = "https://github.com/ntk148v/shibui"
demosite = "https://yogurtthehor.se/"
tags = ["minimalist", "clean", "responsive", "blog", "simple"]
features = ["responsive"]

[author]
name = "ntk148v"
homepage = "https://github.com/ntk148v"

[module]
[module.hugoVersion]
extended = true
min = "0.93.0"
